# Generated by Django 2.2.9 on 2020-01-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Client', verbose_name='거래처'),
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='제품 설명'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=20, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='제품 사진'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantitiy',
            field=models.PositiveIntegerField(verbose_name='남은 수량'),
        ),
    ]
