# Generated by Django 2.2.9 on 2020-01-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200126_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
