# Generated by Django 2.2.9 on 2020-01-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200127_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='management.Client', verbose_name='거래처'),
        ),
    ]
